import streamlit as st
import datetime
import requests
import os
import sys

Base_url = "http://localhost:8000" # Update with your FastAPI server URL

st.set_page_config(
    page_title="🌍 Travel Planner",
    page_icon=":airplane:",
    layout="centered",
    initial_sidebar_state="expanded",
)
st.title("🌍 Travel Planner")


# Intialize session state for messages
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I assist you with your travel plans today?")

with st.form("query_form"):
    user_input = st.text_input("User Input", placeholder="Ask me anything about your travel plans (e.g. Plan a trip to Goa for 5 days)")
    submit_button = st.form_submit_button(label="Submit")

if submit_button and user_input.strip():
    try:
        # Show user input in the chat
        # Show thinking spinner while backend processes the query
        with st.spinner("Planning your trip..."):
            payload = {"query": user_input}
            response = requests.post(f"{Base_url}/query", json=payload)

        if response.status_code == 200:
            data = response.json()
            answer = data.get("answer", "Sorry, I couldn't get an answer.")
            markdown_answer  = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(f"**Travel Planner:** {markdown_answer}")

            # Save the conversation to session state
            st.session_state.messages.append({"role": "user", "content": user_input})
            st.session_state.messages.append({"role": "assistant", "content": answer})
        else:
            st.error(f"Error: {response.status_code} - {response.text}")
    except Exception as e:
        raise f"An error occurred: {str(e)}"
