import os
import datetime

def save_to_doc(content: str, filename: str = "output.md") -> None:
    """
    Export the travel plan to a Markdown file with proper formatting .
    """
    os.makedirs("output", exist_ok=True)

    # Create a Markdown content with Metadata a title and timestamp
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    markdown_content = f"""# Travel Plan

    ## Generated: {timestamp}
    ## Created by: Nitish's Travel Agent
    ---
    {content}
    ---
    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
    try:
        # Write the Markdown content with utf-8 encoding to handle special characters
        # Generate timestamp for filename to avoid overwriting
        timestamp_for_filename = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"output/{filename}_{timestamp_for_filename}.md"
        with open(output_filename, "w", encoding="utf-8") as file:
            file.write(markdown_content)
        print(f"Travel plan saved to {output_filename}")
    except Exception as e:
        print(f"Error saving travel plan: {e}")

        return None